name: build:agent
on:
  pull_request:
    paths:
      - 'examples/**'
      - 'src/**'
      - 'test/**'
      - 'package.json'
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.9
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: cd packages/agent && pnpm run build
      - name: Test
        run: cd packages/agent && pnpm run test
        env:
          CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
